apiVersion: asset.sap/v1
kind: Asset
type: mcp-server

metadata:
  name: sap-s4-ce-freightorder-0001-mcp-server
  version: "1.0.0"
  translation: mcp-translation/translation.json
  apiSpec: mcp-translation/api-spec.edmx

provides:
  apis:
    - name: sap-s4-ce-freightorder-0001-mcp-server
      kind: mcp-server
      ordId: customer.build:apiResource:otd-fix-the-risk-f8547.sap-s4-ce-freightorder-0001-mcp-server:v1

requires:
  - name: CE_FREIGHTORDER_0001
    kind: api
    ordId: sap.s4:apiResource:CE_FREIGHTORDER_0001:v1
